<h1 class="text-title">TIỆN ÍCH</h1>
<div class="ultity">
    <div class="u_p_1">
        <div>DỰ BÁO THỜI TIẾT</div>
        <a href="/du-bao-thoi-tiet">Xem ngay -></a>
    </div>
    <div class="u_p_2">
        <div>TỈ GIÁ TIỀN TỆ</div>
        <a href="/ti-gia-tien-te">Xem ngay -></a>
    </div>

    <div class="u_p_3">
        <div>BẢN TIN KINH DOANH</div>
        <a href="/ban-tin-kinh-doanh">Xem ngay -></a>
    </div>

</div>

<style>
    .footer,
    .copyright {

        letter-spacing: 0.5px;
    }

    .block-title {
        text-align: center;
        font-family: Oswald;
        word-spacing: 3px;
        letter-spacing: 4px;
        color: #070404;
        text-shadow: 0px 1px 4px white;
        text-transform: uppercase;
    }

    .block-title strong {
        font-size: 40px !important;
    }

    .header {

        letter-spacing: 1px;
        color: white;
    }

    .header a {
        font-size: 17px !important;
    }

    .header span {
        font-size: 17px !important;
    }

    .header .authorization-link {
        font-size: 17px !important;
    }

    .text-title {
        text-align: center;
        font-family: Oswald;
        word-spacing: 3px;
        letter-spacing: 4px;
        color: #070404;
        text-shadow: 0px 1px 4px white;
    }

    .ultity {
        width: 100%;
        display: flex;
        color: #082e48;
        font-family: Kanit;
        letter-spacing: 1px;
        font-size: 32px;
        font-weight: bold;
        text-shadow: 0px 1px 2px white;
        padding-bottom: 40px;
    }

    .ultity>div>div {
        -webkit-text-stroke: 0.7px white;
    }

    .ultity a {
        margin-top: 10px;
        color: #ffffff;
        font-family: 'Roboto Condensed';
        text-decoration: none;
        display: inline-block;
        width: 140px;
        text-align: center;
        background: #006bb4;
        border: 1.5px solid white;
        border-radius: 8px;
        padding: 6px 3px;
        font-size: 22px !important;
        transition: 0.2s;
    }

    .ultity a:hover {
        background: #16405d;
    }

    .u_p_1 {
        width: 33.33%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        padding: 105px 30px;
        background-image: url('https://i.imgur.com/DT5Eykx.png');
        background-size: cover
    }

    .u_p_2 {
        width: 33.33%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        padding: 105px 30px;
        background-image: url('https://i.imgur.com/sPYL147.png');
        background-size: cover
    }

    .u_p_3 {
        width: 33.33%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        padding: 105px 30px;
        background-image: url('http://bit.ueh.edu.vn/wp-content/uploads/2017/06/e-commerce.jpg');
        background-size: cover
    }

    .marketing {
        padding: 0px 0px 40px 0px;
        width: 100%;
        display: flex;
    }

    .m_p {
        width: 33.33%;
        padding: 10px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .m_p_img {
        width: 15%;
    }

    .m_p_img img {
        width: 100%;
    }

    .m_p_title {
        padding: 5px;
        width: 85%;
        display: flex;
        flex-direction: column;
        justify-content: center;
    }

    .m_title1 {
        font-weight: bold;
        font-size: 19px;
        padding: 3px;
        color: #070404;
        font-family: 'Roboto Condensed';
        letter-spacing: 1px;
    }

    .m_title2 {
        color: #070404;
        font-family: 'Roboto Condensed';
        letter-spacing: 1px;
        font-size: 16px;
    }
</style>