<strong class="text-title">Tiện Ích</strong>
<div class="ultity">
    <div class="u_p_1">
        <div>DỰ BÁO THỜI TIẾT</div>
        <a href="/du-bao-thoi-tiet">Xem ngay</a>
    </div>
    <div class="u_p_2">
        <div>TỈ GIÁ TIỀN TỆ</div>
        <a href="/ti-gia-tien-te">Xem ngay</a>
    </div>

    <div class="u_p_3">
        <div>BẢN TIN KINH DOANH</div>
        <a href="/ban-tin-kinh-doanh">Xem ngay</a>
    </div>

</div>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap');

    *:not(.socials-block) {
        font-family: 'Playfair Display', serif !important;
    }

    .block-title {
        text-align: center;
        word-spacing: 3px;
        color: #070404;
        text-shadow: 0px 1px 4px white;
        text-transform: uppercase;
    }

    .block-title strong {
        font-size: 22px !important;
    }

    .header {
        color: white;
    }

    .header a {
        font-size: 16px !important;
    }

    .header span {
        font-size: 14px !important;
    }

    .header .authorization-link {
        font-size: 14px !important;
    }

    .page-bottom {
        width: 100% !important;
    }

    .ultity {
        width: 100%;
        display: flex;
        color: #082e48;
        font-size: 22px;
        font-weight: bold;
        text-shadow: 0px 1px 2px white;
        padding-bottom: 40px;
    }

    .ultity>div>div {
        -webkit-text-stroke: 0.3px rgba(38, 38, 129, 1);
    }

    .ultity a {
        margin-top: 10px;
        color: #ffffff;
        text-decoration: none;
        display: inline-block;
        width: 140px;
        text-align: center;
        background: #006bb4;
        border: 1.5px solid white;
        border-radius: 8px;
        padding: 6px 3px;
        font-size: 22px !important;
        transition: 0.2s;
    }

    .ultity a:hover {
        background: #16405d;
    }

    .u_p_1 {
        width: 33.33%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        padding: 105px 30px;
        background-image: url('https://i.imgur.com/DT5Eykx.png');
        background-size: cover
    }

    .u_p_2 {
        width: 33.33%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        padding: 105px 30px;
        background-image: url('https://i.imgur.com/sPYL147.png');
        background-size: cover
    }

    .u_p_3 {
        width: 33.33%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        padding: 105px 30px;
        background-image: url('http://bit.ueh.edu.vn/wp-content/uploads/2017/06/e-commerce.jpg');
        background-size: cover
    }

    .navigation {
        display: flex !important;
        justify-content: center !important;
        align-items: center !important;
        background-color: black !important;
    }

    .navigation a {
        text-decoration: none;
        color: #000;
        transition: 0.2s;
        font-size: 19px;
    }

    .text-title {
        font-size: 22px;
    }
</style>